input_file = [
    {
        "actor1": "Boko Haram - Wilayat Gharb Ifriqiyyah",
        "actor2": "Civilians (Nigeria)",
        "admin1": "Borno",
        "admin2": "Chibok",
        "admin3": null,
        "assoc_actor_1": null,
        "assoc_actor_2": null,
        "country": "Nigeria",
        "data_id": 5119842,
        "event_date": "01 April 2019",
        "event_id_cnty": "NIG14321",
        "event_id_no_cnty": 14321,
        "event_type": "Violence against civilians",
        "fatalities": 0,
        "geo_precision": 1,
        "inter1": 2,
        "inter2": 7,
        "interaction": 27,
        "iso": 566,
        "iso3": "NGA",
        "latitude": 10.8609,
        "location": "Kaumutuyahi",
        "longitude": 12.9623,
        "notes": "01 April. Boko Haram set the Kaumutiyah village on fire.",
        "region": "Western Africa",
        "source": "Vanguard (Nigeria)",
        "source_scale": "National",
        "sub_event_type": "Attack",
        "time_precision": 1,
        "timestamp": 1554749634,
        "year": 2019
    },
    {
        "actor1": "Boko Haram - Wilayat Gharb Ifriqiyyah (Barnawi Faction)",
        "actor2": "Civilians (Nigeria)",
        "admin1": "Borno",
        "admin2": "Maiduguri",
        "admin3": null,
        "assoc_actor_1": null,
        "assoc_actor_2": "Military Forces of Nigeria (2015-); Civilian JTF: Civilian Joint Task Force",
        "country": "Nigeria",
        "data_id": 5119845,
        "event_date": "01 April 2019",
        "event_id_cnty": "NIG14324",
        "event_id_no_cnty": 14324,
        "event_type": "Violence against civilians",
        "fatalities": 5,
        "geo_precision": 3,
        "inter1": 2,
        "inter2": 7,
        "interaction": 27,
        "iso": 566,
        "iso3": "NGA",
        "latitude": 11.8464,
        "location": "Maiduguri",
        "longitude": 13.1603,
        "notes": "01 April. Boko Haram IS published a video showing the execution of five Nigerian soldiers in Borno. Military forces claimed that three of them were members of civilian militias",
        "region": "Western Africa",
        "source": "Vanguard (Nigeria)",
        "source_scale": "National",
        "sub_event_type": "Attack",
        "time_precision": 1,
        "timestamp": 1554749634,
        "year": 2019
    },
    {
        "actor1": "Boko Haram - Wilayat Gharb Ifriqiyyah",
        "actor2": "Civilians (Nigeria)",
        "admin1": "Adamawa",
        "admin2": "Madagali",
        "admin3": null,
        "assoc_actor_1": null,
        "assoc_actor_2": null,
        "country": "Nigeria",
        "data_id": 5168244,
        "event_date": "02 April 2019",
        "event_id_cnty": "NIG13771",
        "event_id_no_cnty": 13771,
        "event_type": "Violence against civilians",
        "fatalities": 1,
        "geo_precision": 1,
        "inter1": 2,
        "inter2": 7,
        "interaction": 27,
        "iso": 566,
        "iso3": "NGA",
        "latitude": 10.7411,
        "location": "Shuwa",
        "longitude": 13.4147,
        "notes": "04 February. Boko Haram stormed Shuwa village in Madagali LGA and killed one person. Nigerian Military Forces deployed troops from nearby Madagali and engaged BH in a battle (coded in separate event). BH was eventually forced to withdraw from Shuwa.",
        "region": "Western Africa",
        "source": "Legit; The Cable (Nigeria); Defense Post",
        "source_scale": "National",
        "sub_event_type": "Attack",
        "time_precision": 1,
        "timestamp": 1557775806,
        "year": 2019
    },
    {
        "actor1": "Boko Haram - Wilayat Gharb Ifriqiyyah",
        "actor2": "Civilians (Nigeria)",
        "admin1": "Adamawa",
        "admin2": "Madagali",
        "admin3": null,
        "assoc_actor_1": null,
        "assoc_actor_2": null,
        "country": "Nigeria",
        "data_id": 5168245,
        "event_date": "02 April 2019",
        "event_id_cnty": "NIG13784",
        "event_id_no_cnty": 13784,
        "event_type": "Strategic developments",
        "fatalities": 0,
        "geo_precision": 2,
        "inter1": 2,
        "inter2": 7,
        "interaction": 27,
        "iso": 566,
        "iso3": "NGA",
        "latitude": 10.8864,
        "location": "Madagali",
        "longitude": 13.63,
        "notes": "04 February. Boko Haram looted Shuari and Kishingari village near Madagali.",
        "region": "Western Africa",
        "source": "Daily Post (Nigeria)",
        "source_scale": "National",
        "sub_event_type": "Looting/property destruction",
        "time_precision": 1,
        "timestamp": 1557775806,
        "year": 2019
    },
    {
        "actor1": "Boko Haram - Wilayat Gharb Ifriqiyyah (Barnawi Faction)",
        "actor2": "MNJTF: Multinational Joint Task Force",
        "admin1": "Diffa",
        "admin2": "Diffa",
        "admin3": "Toumour",
        "assoc_actor_1": null,
        "assoc_actor_2": null,
        "country": "Niger",
        "data_id": 5119829,
        "event_date": "02 April 2019",
        "event_id_cnty": "NIR842",
        "event_id_no_cnty": 842,
        "event_type": "Explosions/Remote violence",
        "fatalities": 3,
        "geo_precision": 2,
        "inter1": 2,
        "inter2": 8,
        "interaction": 28,
        "iso": 562,
        "iso3": "NER",
        "latitude": 13.6669,
        "location": "Toumour",
        "longitude": 13.1198,
        "notes": "On April 2, ISWAP claimed to have detonated an IED against a vehicle of the Multinational Joint Task Force near Toumour, killing the occupants of the vehicle, unknown fatalities coded at low estimate of 3.",
        "region": "Western Africa",
        "source": "Amaq; Nashir News Agency",
        "source_scale": "Other-Regional",
        "sub_event_type": "Remote explosive/landmine/IED",
        "time_precision": 1,
        "timestamp": 1554749634,
        "year": 2019
    },
    {
        "actor1": "Boko Haram - Wilayat Gharb Ifriqiyyah",
        "actor2": "Civilians (Nigeria)",
        "admin1": "Borno",
        "admin2": "Maiduguri",
        "admin3": null,
        "assoc_actor_1": null,
        "assoc_actor_2": null,
        "country": "Nigeria",
        "data_id": 5127092,
        "event_date": "06 April 2019",
        "event_id_cnty": "NIG14376",
        "event_id_no_cnty": 14376,
        "event_type": "Explosions/Remote violence",
        "fatalities": 5,
        "geo_precision": 1,
        "inter1": 2,
        "inter2": 7,
        "interaction": 27,
        "iso": 566,
        "iso3": "NGA",
        "latitude": 11.8464,
        "location": "Maiduguri",
        "longitude": 13.1603,
        "notes": "06 April. Two Boko Haram suicide bombers killed themselves and three civilians in the outskirts of Maiduguri when their IED vests detonated in the Muna-Dalti area of the city. 45 people were injured.",
        "region": "Western Africa",
        "source": "Daily Post (Nigeria)",
        "source_scale": "National",
        "sub_event_type": "Suicide bomb",
        "time_precision": 1,
        "timestamp": 1555346747,
        "year": 2019
    },
    {
        "actor1": "Boko Haram - Wilayat Gharb Ifriqiyyah",
        "actor2": "Civilians (Niger)",
        "admin1": "Diffa",
        "admin2": "Diffa",
        "admin3": "Toumour",
        "assoc_actor_1": null,
        "assoc_actor_2": null,
        "country": "Niger",
        "data_id": 5127053,
        "event_date": "08 April 2019",
        "event_id_cnty": "NIR848",
        "event_id_no_cnty": 848,
        "event_type": "Violence against civilians",
        "fatalities": 2,
        "geo_precision": 1,
        "inter1": 2,
        "inter2": 7,
        "interaction": 27,
        "iso": 562,
        "iso3": "NER",
        "latitude": 13.6669,
        "location": "Toumour",
        "longitude": 13.1198,
        "notes": "On April 8, presumed ISWAP/Boko Haram militants carried out an incursion into the area of Toumour, two civilians killed including one had the throat slit and the other shot dead, and a notable wounded.",
        "region": "Western Africa",
        "source": "Urgence Diffa",
        "source_scale": "Other",
        "sub_event_type": "Attack",
        "time_precision": 1,
        "timestamp": 1555346747,
        "year": 2019
    },
    {
        "actor1": "Boko Haram - Wilayat Gharb Ifriqiyyah (Barnawi Faction)",
        "actor2": "Military Forces of Niger (2011-)",
        "admin1": "Diffa",
        "admin2": "Diffa",
        "admin3": "Diffa",
        "assoc_actor_1": null,
        "assoc_actor_2": "MNJTF: Multinational Joint Task Force",
        "country": "Niger",
        "data_id": 5127054,
        "event_date": "08 April 2019",
        "event_id_cnty": "NIR849",
        "event_id_no_cnty": 849,
        "event_type": "Explosions/Remote violence",
        "fatalities": 0,
        "geo_precision": 1,
        "inter1": 2,
        "inter2": 1,
        "interaction": 12,
        "iso": 562,
        "iso3": "NER",
        "latitude": 13.32,
        "location": "Diffa",
        "longitude": 12.61,
        "notes": "On April 8, ISWAP militants launched a barrage of Grad rockets targeting the Diffa Airport harboring the Multinational Joint Task Force and the military base, the attack did not cause any casualties, and the projectiles fell hundred meters outside the perimeter of the facilities.",
        "region": "Western Africa",
        "source": "Jeunesse Diffa; Nashir News Agency",
        "source_scale": "Other",
        "sub_event_type": "Shelling/artillery/missile attack",
        "time_precision": 1,
        "timestamp": 1555346747,
        "year": 2019
    },
    {
        "actor1": "Boko Haram - Wilayat Gharb Ifriqiyyah (Barnawi Faction)",
        "actor2": "Military Forces of Nigeria (2015-)",
        "admin1": "Yobe",
        "admin2": "Damaturu",
        "admin3": null,
        "assoc_actor_1": null,
        "assoc_actor_2": null,
        "country": "Nigeria",
        "data_id": 5170666,
        "event_date": "09 April 2019",
        "event_id_cnty": "NIG14395",
        "event_id_no_cnty": 14395,
        "event_type": "Battles",
        "fatalities": 0,
        "geo_precision": 1,
        "inter1": 2,
        "inter2": 1,
        "interaction": 12,
        "iso": 566,
        "iso3": "NGA",
        "latitude": 11.747,
        "location": "Damaturu",
        "longitude": 11.9608,
        "notes": "09 April. Boko Haram IS attacked Damaturu and engaged in a battle with Nigerian Military Forces. Military forces seized gun trucks and weapons. No fatalities reported yet.",
        "region": "Western Africa",
        "source": "Vanguard (Nigeria)",
        "source_scale": "National",
        "sub_event_type": "Armed clash",
        "time_precision": 1,
        "timestamp": 1557782382,
        "year": 2019
    },
    {
        "actor1": "Boko Haram - Wilayat Gharb Ifriqiyyah",
        "actor2": "Civilians (Niger)",
        "admin1": "Diffa",
        "admin2": "Maine Soroa",
        "admin3": "Maine Soroa",
        "assoc_actor_1": null,
        "assoc_actor_2": "Unidentified Clan Group (Niger)",
        "country": "Niger",
        "data_id": 5127056,
        "event_date": "09 April 2019",
        "event_id_cnty": "NIR851",
        "event_id_no_cnty": 851,
        "event_type": "Violence against civilians",
        "fatalities": 1,
        "geo_precision": 1,
        "inter1": 2,
        "inter2": 7,
        "interaction": 27,
        "iso": 562,
        "iso3": "NER",
        "latitude": 13.1405,
        "location": "Gremari",
        "longitude": 12.1673,
        "notes": "On April 9, presumed ISWAP/Boko Haram militants killed the village chief in Gremari and abducted two individuals including the father and the niece of the secretary general at the mayor's office of Maine Soroa.",
        "region": "Western Africa",
        "source": "Urgence Diffa; Jeunesse Diffa; Actu (Niger)",
        "source_scale": "Other-National",
        "sub_event_type": "Attack",
        "time_precision": 1,
        "timestamp": 1555346747,
        "year": 2019
    },
    {
        "actor1": "Boko Haram - Wilayat Gharb Ifriqiyyah (Barnawi Faction)",
        "actor2": "Military Forces of Niger (2011-) Gendarmerie",
        "admin1": "Diffa",
        "admin2": "Diffa",
        "admin3": "Diffa",
        "assoc_actor_1": null,
        "assoc_actor_2": null,
        "country": "Niger",
        "data_id": 5127057,
        "event_date": "09 April 2019",
        "event_id_cnty": "NIR852",
        "event_id_no_cnty": 852,
        "event_type": "Battles",
        "fatalities": 6,
        "geo_precision": 1,
        "inter1": 2,
        "inter2": 1,
        "interaction": 12,
        "iso": 562,
        "iso3": "NER",
        "latitude": 13.32,
        "location": "Diffa",
        "longitude": 12.61,
        "notes": "On April 9, four ISWAP militants equipped with small arms and hand grenades attacked the town of Diffa, they targeted the gendarmerie and the customs, clashes raged overnight and two gendarmes were killed and at least four gendarmes wounded, all assailants killed.",
        "region": "Western Africa",
        "source": "Xinhua; AFP; RFI; Actu (Niger); Amaq; Nashir News Agency",
        "source_scale": "Other-National",
        "sub_event_type": "Armed clash",
        "time_precision": 1,
        "timestamp": 1555346747,
        "year": 2019
    },
    {
        "actor1": "Boko Haram - Wilayat Gharb Ifriqiyyah (Barnawi Faction)",
        "actor2": "MNJTF: Multinational Joint Task Force",
        "admin1": "Diffa",
        "admin2": "Diffa",
        "admin3": "Toumour",
        "assoc_actor_1": null,
        "assoc_actor_2": null,
        "country": "Niger",
        "data_id": 5127058,
        "event_date": "10 April 2019",
        "event_id_cnty": "NIR853",
        "event_id_no_cnty": 853,
        "event_type": "Explosions/Remote violence",
        "fatalities": 3,
        "geo_precision": 2,
        "inter1": 2,
        "inter2": 8,
        "interaction": 28,
        "iso": 562,
        "iso3": "NER",
        "latitude": 13.6669,
        "location": "Toumour",
        "longitude": 13.1198,
        "notes": "On April 10, ISWAP claimed destroying a vehicle of the Multinational Joint Task Force by detonation of an IED near Toumour, and killing and wounding seven of the occupants, fatalities coded as 3.",
        "region": "Western Africa",
        "source": "Nashir News Agency",
        "source_scale": "Other",
        "sub_event_type": "Remote explosive/landmine/IED",
        "time_precision": 1,
        "timestamp": 1555346747,
        "year": 2019
    },
    {
        "actor1": "Boko Haram - Wilayat Gharb Ifriqiyyah",
        "actor2": "Civilians (Niger)",
        "admin1": "Diffa",
        "admin2": "Diffa",
        "admin3": "Bosso",
        "assoc_actor_1": null,
        "assoc_actor_2": null,
        "country": "Niger",
        "data_id": 5127059,
        "event_date": "11 April 2019",
        "event_id_cnty": "NIR854",
        "event_id_no_cnty": 854,
        "event_type": "Explosions/Remote violence",
        "fatalities": 2,
        "geo_precision": 2,
        "inter1": 2,
        "inter2": 7,
        "interaction": 27,
        "iso": 562,
        "iso3": "NER",
        "latitude": 13.522,
        "location": "Bouji",
        "longitude": 13.0891,
        "notes": "On April 11, a plow was struck by an IED presumably planted by ISWAP/Boko Haram militants in the area of Bougi, two civilians were killed, one wounded, as well as livestock killed.",
        "region": "Western Africa",
        "source": "Urgence Diffa; Toute l'actualite sur Diffa; Jeunesse Diffa",
        "source_scale": "Other",
        "sub_event_type": "Remote explosive/landmine/IED",
        "time_precision": 1,
        "timestamp": 1555346747,
        "year": 2019
    },
    {
        "actor1": "Boko Haram - Wilayat Gharb Ifriqiyyah (Barnawi Faction)",
        "actor2": "MNJTF: Multinational Joint Task Force",
        "admin1": "Diffa",
        "admin2": "Diffa",
        "admin3": "Toumour",
        "assoc_actor_1": null,
        "assoc_actor_2": null,
        "country": "Niger",
        "data_id": 5127061,
        "event_date": "12 April 2019",
        "event_id_cnty": "NIR856",
        "event_id_no_cnty": 856,
        "event_type": "Explosions/Remote violence",
        "fatalities": 3,
        "geo_precision": 2,
        "inter1": 2,
        "inter2": 8,
        "interaction": 28,
        "iso": 562,
        "iso3": "NER",
        "latitude": 13.6669,
        "location": "Toumour",
        "longitude": 13.1198,
        "notes": "On April 12, ISWAP claimed destroying a tank of the Multinational Joint Task Force by detonation of an IED near Toumour, and killing the occupants, unknown fatalities coded as 3.",
        "region": "Western Africa",
        "source": "Nashir News Agency",
        "source_scale": "Other",
        "sub_event_type": "Remote explosive/landmine/IED",
        "time_precision": 1,
        "timestamp": 1555346747,
        "year": 2019
    },
    {
        "actor1": "Boko Haram - Wilayat Gharb Ifriqiyyah",
        "actor2": "Civilians (Niger)",
        "admin1": "Diffa",
        "admin2": "Diffa",
        "admin3": "Chetimari",
        "assoc_actor_1": null,
        "assoc_actor_2": null,
        "country": "Niger",
        "data_id": 5127062,
        "event_date": "13 April 2019",
        "event_id_cnty": "NIR857",
        "event_id_no_cnty": 857,
        "event_type": "Violence against civilians",
        "fatalities": 1,
        "geo_precision": 1,
        "inter1": 2,
        "inter2": 7,
        "interaction": 27,
        "iso": 562,
        "iso3": "NER",
        "latitude": 13.1592,
        "location": "Biri Boula",
        "longitude": 12.355,
        "notes": "On April 13, presumed ISWAP/Boko Haram militants aboard motorbikes shot dead an individual and burned the corps in Biri Boula.",
        "region": "Western Africa",
        "source": "Jeunesse DIFFA",
        "source_scale": "Other",
        "sub_event_type": "Attack",
        "time_precision": 1,
        "timestamp": 1555346747,
        "year": 2019
    },
    {
        "actor1": "Boko Haram - Wilayat Gharb Ifriqiyyah (Barnawi Faction)",
        "actor2": "Civilians (Nigeria)",
        "admin1": "Borno",
        "admin2": "Chibok",
        "admin3": null,
        "assoc_actor_1": null,
        "assoc_actor_2": null,
        "country": "Nigeria",
        "data_id": 5131055,
        "event_date": "14 April 2019",
        "event_id_cnty": "NIG14429",
        "event_id_no_cnty": 14429,
        "event_type": "Violence against civilians",
        "fatalities": 0,
        "geo_precision": 1,
        "inter1": 2,
        "inter2": 7,
        "interaction": 27,
        "iso": 566,
        "iso3": "NGA",
        "latitude": 10.8549,
        "location": "Korongelen Bula Dun*",
        "longitude": 12.7157,
        "notes": "14 April: Boko Haram militants raided the Kwarangulum village (16 KMs from Chibok town) and set several homes on fire after looting food and other necessary items. The residents escaped when they saw that some group of armed men were coming toward them. No casualties reported",
        "region": "Western Africa",
        "source": "Vanguard (Nigeria)",
        "source_scale": "National",
        "sub_event_type": "Attack",
        "time_precision": 1,
        "timestamp": 1555958740,
        "year": 2019
    },
    {
        "actor1": "Boko Haram - Wilayat Gharb Ifriqiyyah (Barnawi Faction)",
        "actor2": "Military Forces of Chad (1990-)",
        "admin1": "Borno",
        "admin2": "Kukawa",
        "admin3": null,
        "assoc_actor_1": null,
        "assoc_actor_2": null,
        "country": "Nigeria",
        "data_id": 5131068,
        "event_date": "16 April 2019",
        "event_id_cnty": "NIG14442",
        "event_id_no_cnty": 14442,
        "event_type": "Battles",
        "fatalities": 55,
        "geo_precision": 1,
        "inter1": 2,
        "inter2": 8,
        "interaction": 28,
        "iso": 566,
        "iso3": "NGA",
        "latitude": 12.9452,
        "location": "Cross Kauwa",
        "longitude": 13.6723,
        "notes": "16 April: Boko Haram attacked Chadian soldiers in Cross Kaura in the Magorone area (100 KMs north of Maiduguri) and killed two. Military repeled them kiling 53. Chadian soldiers were sent to Nigeria end February to support Nigerian soldiers in defeating Boko Haram",
        "region": "Western Africa",
        "source": "BBC Monitoring",
        "source_scale": "International",
        "sub_event_type": "Armed clash",
        "time_precision": 1,
        "timestamp": 1555958740,
        "year": 2019
    },
    {
        "actor1": "Boko Haram - Wilayat Gharb Ifriqiyyah",
        "actor2": "Civilians (Niger)",
        "admin1": "Diffa",
        "admin2": "Diffa",
        "admin3": "Diffa",
        "assoc_actor_1": null,
        "assoc_actor_2": "Health Workers (Niger)",
        "country": "Niger",
        "data_id": 5146499,
        "event_date": "20 April 2019",
        "event_id_cnty": "NIR863",
        "event_id_no_cnty": 863,
        "event_type": "Strategic developments",
        "fatalities": 0,
        "geo_precision": 1,
        "inter1": 2,
        "inter2": 7,
        "interaction": 27,
        "iso": 562,
        "iso3": "NER",
        "latitude": 13.379,
        "location": "Ngarwa-Koura",
        "longitude": 12.7569,
        "notes": "On April 20, presumed ISWAP/Boko Haram militants seized solar panels from the medical center in Ngarwa-Koura.",
        "region": "Western Africa",
        "source": "Urgence Diffa; Jeunesse DIFFA",
        "source_scale": "Other",
        "sub_event_type": "Looting/property destruction",
        "time_precision": 1,
        "timestamp": 1556572283,
        "year": 2019
    },
    {
        "actor1": "Boko Haram - Wilayat Gharb Ifriqiyyah",
        "actor2": "Civilians (Niger)",
        "admin1": "Diffa",
        "admin2": "N'Guigmi",
        "admin3": "N Guigmi",
        "assoc_actor_1": null,
        "assoc_actor_2": "Fishermen (Niger)",
        "country": "Niger",
        "data_id": 5146500,
        "event_date": "22 April 2019",
        "event_id_cnty": "NIR864",
        "event_id_no_cnty": 864,
        "event_type": "Violence against civilians",
        "fatalities": 0,
        "geo_precision": 1,
        "inter1": 2,
        "inter2": 7,
        "interaction": 27,
        "iso": 562,
        "iso3": "NER",
        "latitude": 14.2495,
        "location": "N Guigmi",
        "longitude": 13.1092,
        "notes": "On April 22, presumed ISWAP/Boko Haram militants opened fire against three fishermen who were travelling between the island of Fefea and Nguigmi, two escaped while one was hit by bullets and his fate remains unknown.",
        "region": "Western Africa",
        "source": "Jeunesse DIFFA",
        "source_scale": "Other",
        "sub_event_type": "Attack",
        "time_precision": 1,
        "timestamp": 1556572283,
        "year": 2019
    },
    {
        "actor1": "Boko Haram - Wilayat Gharb Ifriqiyyah (Barnawi Faction)",
        "actor2": "Military Forces of Niger (2011-)",
        "admin1": "Diffa",
        "admin2": "Diffa",
        "admin3": "Toumour",
        "assoc_actor_1": null,
        "assoc_actor_2": null,
        "country": "Niger",
        "data_id": 5146501,
        "event_date": "23 April 2019",
        "event_id_cnty": "NIR865",
        "event_id_no_cnty": 865,
        "event_type": "Explosions/Remote violence",
        "fatalities": 3,
        "geo_precision": 2,
        "inter1": 2,
        "inter2": 1,
        "interaction": 12,
        "iso": 562,
        "iso3": "NER",
        "latitude": 13.6669,
        "location": "Toumour",
        "longitude": 13.1198,
        "notes": "On April 23, ISWAP claimed to have destroyed an army vehicle by IED detonation in the area of Toumour and killing and wounding the occupants (unknown fatalities coded at low estimate of 3). No reports corroborate the claim.",
        "region": "Western Africa",
        "source": "Amaq; Nashir News Agency",
        "source_scale": "Other-Regional",
        "sub_event_type": "Remote explosive/landmine/IED",
        "time_precision": 1,
        "timestamp": 1556572283,
        "year": 2019
    },
    {
        "actor1": "Boko Haram - Wilayat Gharb Ifriqiyyah (Barnawi Faction)",
        "actor2": "Military Forces of Niger (2011-)",
        "admin1": "Diffa",
        "admin2": "Diffa",
        "admin3": "Toumour",
        "assoc_actor_1": null,
        "assoc_actor_2": null,
        "country": "Niger",
        "data_id": 5146502,
        "event_date": "23 April 2019",
        "event_id_cnty": "NIR866",
        "event_id_no_cnty": 866,
        "event_type": "Battles",
        "fatalities": 10,
        "geo_precision": 2,
        "inter1": 2,
        "inter2": 1,
        "interaction": 12,
        "iso": 562,
        "iso3": "NER",
        "latitude": 13.6669,
        "location": "Toumour",
        "longitude": 13.1198,
        "notes": "On April 23, ISWAP claimed to have attacked army barracks in Toumour and killing and wounding an unspecified number of soldiers. Unknown fatalities coded as 10. No reports corroborate the claim.",
        "region": "Western Africa",
        "source": "Nashir News Agency",
        "source_scale": "Other",
        "sub_event_type": "Armed clash",
        "time_precision": 1,
        "timestamp": 1556572283,
        "year": 2019
    },
    {
        "actor1": "Boko Haram - Wilayat Gharb Ifriqiyyah (Barnawi Faction)",
        "actor2": "Military Forces of Niger (2011-)",
        "admin1": "Diffa",
        "admin2": "Diffa",
        "admin3": "Toumour",
        "assoc_actor_1": null,
        "assoc_actor_2": null,
        "country": "Niger",
        "data_id": 5146503,
        "event_date": "24 April 2019",
        "event_id_cnty": "NIR867",
        "event_id_no_cnty": 867,
        "event_type": "Explosions/Remote violence",
        "fatalities": 3,
        "geo_precision": 2,
        "inter1": 2,
        "inter2": 1,
        "interaction": 12,
        "iso": 562,
        "iso3": "NER",
        "latitude": 13.6669,
        "location": "Toumour",
        "longitude": 13.1198,
        "notes": "On April 24, ISWAP claimed to have destroyed an army tank by IED detonation in the area of Toumour and killing the occupants (unknown fatalities coded at low estimate of 3). No reports corroborate the claim.",
        "region": "Western Africa",
        "source": "Nashir News Agency; Amaq",
        "source_scale": "Other-Regional",
        "sub_event_type": "Remote explosive/landmine/IED",
        "time_precision": 1,
        "timestamp": 1556572283,
        "year": 2019
    },
    {
        "actor1": "Boko Haram - Wilayat Gharb Ifriqiyyah",
        "actor2": "Civilians (Niger)",
        "admin1": "Diffa",
        "admin2": "Maine Soroa",
        "admin3": "Maine Soroa",
        "assoc_actor_1": null,
        "assoc_actor_2": "Private Security Forces (Niger); MSF: Doctors Without Borders",
        "country": "Niger",
        "data_id": 5146505,
        "event_date": "26 April 2019",
        "event_id_cnty": "NIR869",
        "event_id_no_cnty": 869,
        "event_type": "Violence against civilians",
        "fatalities": 0,
        "geo_precision": 1,
        "inter1": 2,
        "inter2": 7,
        "interaction": 27,
        "iso": 562,
        "iso3": "NER",
        "latitude": 13.2114,
        "location": "Maine Soroa",
        "longitude": 12.0241,
        "notes": "On April 26, presumed ISWAP/Boko Haram militants attacked the offices of Doctors without borders in Maine Soroa, one civilian guard was wounded, the offices and vehicles were ransacked and burned.",
        "region": "Western Africa",
        "source": "AFP; Actu (Niger); Aniamey",
        "source_scale": "National-International",
        "sub_event_type": "Attack",
        "time_precision": 1,
        "timestamp": 1556572283,
        "year": 2019
    },
    {
        "actor1": "Boko Haram - Wilayat Gharb Ifriqiyyah",
        "actor2": "Civilians (Niger)",
        "admin1": "Diffa",
        "admin2": "N'Guigmi",
        "admin3": "Kabelawa",
        "assoc_actor_1": null,
        "assoc_actor_2": "Fishermen (Niger)",
        "country": "Niger",
        "data_id": 5146507,
        "event_date": "27 April 2019",
        "event_id_cnty": "NIR871",
        "event_id_no_cnty": 871,
        "event_type": "Violence against civilians",
        "fatalities": 5,
        "geo_precision": 1,
        "inter1": 2,
        "inter2": 7,
        "interaction": 27,
        "iso": 562,
        "iso3": "NER",
        "latitude": 14.0917,
        "location": "Doro Lelewa",
        "longitude": 13.459,
        "notes": "On April 27, presumed ISWAP/Boko Haram militants shot dead at least five fishermen in Doro Lelewa.",
        "region": "Western Africa",
        "source": "Jeunesse DIFFA",
        "source_scale": "Other",
        "sub_event_type": "Attack",
        "time_precision": 1,
        "timestamp": 1556572283,
        "year": 2019
    },
    {
        "actor1": "Boko Haram - Wilayat Gharb Ifriqiyyah",
        "actor2": "Civilians (Nigeria)",
        "admin1": "Borno",
        "admin2": "Nganzai",
        "admin3": null,
        "assoc_actor_1": null,
        "assoc_actor_2": null,
        "country": "Nigeria",
        "data_id": 5162379,
        "event_date": "29 April 2019",
        "event_id_cnty": "NIG14505",
        "event_id_no_cnty": 14505,
        "event_type": "Violence against civilians",
        "fatalities": 30,
        "geo_precision": 1,
        "inter1": 2,
        "inter2": 7,
        "interaction": 27,
        "iso": 566,
        "iso3": "NGA",
        "latitude": 12.5056,
        "location": "Kuda",
        "longitude": 13.1414,
        "notes": "29 April. Boko Haram attacked Kuda and shot down villagers. 30 residents were killed.",
        "region": "Western Africa",
        "source": "Vanguard (Nigeria); Legit",
        "source_scale": "National",
        "sub_event_type": "Attack",
        "time_precision": 1,
        "timestamp": 1557247986,
        "year": 2019
    },
    {
        "actor1": "Boko Haram - Wilayat Gharb Ifriqiyyah (Barnawi Faction)",
        "actor2": "Civilians (Nigeria)",
        "admin1": "Borno",
        "admin2": "Monguno",
        "admin3": null,
        "assoc_actor_1": null,
        "assoc_actor_2": null,
        "country": "Nigeria",
        "data_id": 5162439,
        "event_date": "30 April 2019",
        "event_id_cnty": "NIG14515",
        "event_id_no_cnty": 14515,
        "event_type": "Violence against civilians",
        "fatalities": 14,
        "geo_precision": 1,
        "inter1": 2,
        "inter2": 7,
        "interaction": 27,
        "iso": 566,
        "iso3": "NGA",
        "latitude": 12.6363,
        "location": "Duwabayi",
        "longitude": 13.5594,
        "notes": "30 April. Boko Haram IS forces killed 14 loggers at Duwabayi village.",
        "region": "Western Africa",
        "source": "Vanguard (Nigeria)",
        "source_scale": "National",
        "sub_event_type": "Attack",
        "time_precision": 1,
        "timestamp": 1557247986,
        "year": 2019
    }
]